### ISSUE TITLE
matplotlib markers?

### ISSUE THREAD

**Issue by mdboom** [astrofrog/mpl-scatter-density#2]
Have you considered using markers for this?  Replacing the rasterized scatter calls in example.py with:

ax.plot(x, y, '+', markersize=2, markeredgecolor='red', antialiased=False)

runs in about 2.1s, on my machine.  rasterized_scatter runs in about 1.9s, so it is slightly faster, but not by much.

The interactive performance of matplotlib markers is actually better because it isn't reallocating an image buffer on each pan and zoom.

About the only time to use scatter over marker is when the size of the symbol changes with each instance.

If rasterized output in the file is what you want, you can call "set_rasterized(True)" on the Line2D objects.

**Comment by astrofrog** [comment]
@mdboom @ChrisBeaumont - I'm going to close this: the code here has evolved a bit since it started off, and the performance is higher than what can be done with the various backends, and allows for the colormap-coding (which ``','`` does not). I've however opened #5 and #6 which would be necessary in order to have a full equivalent to the ``c=`` option in scatter.
